import{FormEvent,useMemo,useState}from'react';import{AlertTriangle,ArrowRight,BookOpenCheck,Database,ExternalLink,LoaderCircle,Search,Send}from'lucide-react';import{Link,useLocation,useNavigate}from'react-router-dom';import{ask}from'./api';import{readContext}from'./context';import{show}from'./display';import type{AnswerCard,Claim,Response,StreamEvent}from'./types';

function Table({rows}:{rows:Array<Record<string,unknown>>}){const cols=useMemo(()=>Array.from(new Set(rows.flatMap(Object.keys))).filter(x=>x!=='row_id'),[rows]);if(!rows.length)return null;return <div className="table-scroll" tabIndex={0}><table><thead><tr>{cols.map(c=><th key={c}>{show(c)}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={String(r.row_id)}>{cols.map(c=><td key={c}>{show(r[c])}</td>)}</tr>)}</tbody></table></div>}
function Claims({claims}:{claims:Claim[]}){return claims.length?<section><h2>分析</h2>{claims.map((c,i)=><article className="claim" key={`${c.backing.ref}-${i}`}><p>{c.text}</p><small>{show(c.claim_type)} · {show(c.backing.kind)}: {show(c.backing.ref)}</small></article>)}</section>:null}
function Inspector({card}:{card:AnswerCard}){return <aside className="inspector"><header><BookOpenCheck size={17}/><h2>证据检查器</h2></header><section><h3>Lens 调用</h3>{card.lens_invocations.map(x=><article key={String(x.release_id)}><strong>{show(x.release_id)}</strong><span>{show(x.lens_kind)} / {show(x.release_role)}</span><p>{show(x.contributed_section)}</p></article>)}</section><section><h3>新鲜度</h3>{Object.entries(card.source_freshness).map(([k,v])=><div className="kv" key={k}><span>{show(k)}</span><strong>{v}</strong></div>)}</section><section><h3>出处</h3>{card.provenance.map(x=><p className="source" key={x}>{x}</p>)}</section></aside>}
function Answer({card,claims}:{card:AnswerCard;claims:Claim[]}){const stock=card.object_ref.match(/stock:(\d{6})/)?.[1];return <article className="answer"><header className="answer-head"><div><p className="eyebrow">{show(card.view)} · 截至 {card.as_of}</p><h1>{card.question}</h1></div>{stock&&<Link className="small-button" to={`/stocks/${stock}`}>查看个股<ExternalLink size={14}/></Link>}</header><div className="meta"><b>{show(card.evidence_grade)}</b><span>{card.sample_scope}</span></div><Claims claims={claims.length?claims:card.analysis_claims}/><section><h2>证据菜单</h2><Table rows={card.body_rows}/></section>{card.lens_gap.length>0&&<div className="callout gap"><AlertTriangle size={18}/><div><h2>Lens 缺口</h2>{card.lens_gap.map(x=><p key={String(x.gap_id)}>{show(x.missing_for)}：{show(x.note)}</p>)}</div></div>}{card.data_debt.length>0&&<div className="callout debt"><Database size={18}/><div><h2>数据债</h2>{card.data_debt.map(x=><p key={String(x.debt_ref)}>{show(x.gap)} · {show(x.affects)} · {show(x.debt_ref)}</p>)}</div></div>}<section className="caveats"><h2>边界</h2>{card.caveats.map(x=><p key={x}>{x}</p>)}</section></article>}

export function Copilot(){const location=useLocation(),navigate=useNavigate(),context=useMemo(()=>readContext(location.search),[location.search]);const[question,setQuestion]=useState(context.active_question??'');const[events,setEvents]=useState<StreamEvent[]>([]);const[response,setResponse]=useState<Response|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState('');
async function submit(e:FormEvent){e.preventDefault();const q=question.trim();if(!q||busy)return;setEvents([]);setResponse(null);setError('');setBusy(true);const p=new URLSearchParams(location.search);p.set('question',q);navigate(`/?${p}`,{replace:true});try{await ask(q,{...context,active_question:q},event=>{setEvents(v=>[...v,event]);if(event.event==='completed'&&event.payload.response)setResponse(event.payload.response as Response);if(event.event==='error')setError(String(event.payload.message??'研究请求失败'))})}catch(e){setError(e instanceof Error?e.message:'研究服务不可用')}finally{setBusy(false)}}
const stage=events.some(x=>x.event==='completed')?4:events.some(x=>x.event==='answer_card')?3:events.some(x=>x.event==='routed')?2:events.some(x=>x.event==='interpreted')?1:0;return <div className="copilot"><div className="ask-zone"><header className="page-head"><div><p className="eyebrow">私人 ST 历史研究</p><h1>证据问答</h1></div>{context.symbol&&<Link to={`/stocks/${context.symbol}`}>{context.symbol}<ArrowRight size={14}/></Link>}</header><form className="composer" onSubmit={submit}><Search size={19}/><textarea aria-label="研究问题" value={question} onChange={e=>setQuestion(e.target.value)} placeholder="输入股票、事件或开放研究问题" rows={2}/><button aria-label="提交" disabled={busy||!question.trim()}>{busy?<LoaderCircle className="spin" size={18}/>:<Send size={18}/>}</button></form>{events.length>0&&<ol className="stages">{['解释问题','确定路径','查询证据','校验回答'].map((x,i)=><li className={i<stage?'done':i===stage&&busy?'active':''} key={x}>{x}</li>)}</ol>}{error&&<div className="error"><AlertTriangle size={18}/>{error}</div>}{!response&&!busy&&!error&&<div className="empty">等待研究问题</div>}{response?.degraded_reasons.map(x=><div className="degraded" key={x}>{x}</div>)}{response&&!response.answer_card&&<div className="fallback"><p className="eyebrow">{show(response.route.route)}</p><h2>{show(response.gaps[0]?.description??'当前没有可执行的证据路径')}</h2>{response.sedimentation_candidates.map((x,i)=><p key={i}>{show(x.reason)}</p>)}</div>}</div>{response?.answer_card&&<div className="answer-grid"><Answer card={response.answer_card} claims={response.claims}/><Inspector card={response.answer_card}/></div>}</div>}
